'use client';
import {useState,useEffect,useCallback,useMemo} from 'react';
import {Flag,ArrowUpRight,RefreshCw,ChevronRight,Trophy,Zap,Info,ArrowRight,Check} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {capacity,project,projectConstructors,contenderStatus,isSafe} from '@/lib/championship.mjs';
import snapshot from '@/lib/snapshot.json';
import type {Season,Driver,Championship} from '@/lib/types';
import {OfficialImage,CircuitImage} from '@/components/official-image';
import SeasonResults from './season-results';
const date=(s:string)=>new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(s));
const positionLabel=(p:number)=>p===11?'Outside points / DNF':`P${p}`;
const short=(d:Driver)=>d.name.split(' ').slice(1).join(' ');
type Scenario='pressure'|'earliest'|'custom';
export default function App(){
 const [season,setSeason]=useState<Season>(snapshot as Season);
 const [selected,setSelected]=useState(snapshot.drivers[0].id);
 const [championship,setChampionship]=useState<Championship>('drivers');
 const [selectedConstructor,setSelectedConstructor]=useState(snapshot.constructors[0].id);
 const [ownPair,setOwnPair]=useState([1,2]),[rivalPair,setRivalPair]=useState([3,4]);
 const [mode,setMode]=useState<Scenario>('pressure');
 const [own,setOwn]=useState(1),[rival,setRival]=useState(2);
 const [showAll,setShowAll]=useState(false),[busy,setBusy]=useState(false),[verified,setVerified]=useState(false),[error,setError]=useState('');
 const [hover,setHover]=useState<number|null>(null);
 const refresh=useCallback(async()=>{setBusy(true);setError('');try{const r=await fetch('/api/season');const data=await r.json() as Season & {error?:string};if(!r.ok)throw new Error(data.error);if(!Array.isArray(data.constructors)||!Array.isArray(data.drivers))throw new Error('Restart the local server to load the updated championship data.');setSeason(data);setVerified(true);setSelectedConstructor(id=>data.constructors.some(c=>c.id===id)?id:data.constructors[0].id);setSelected(id=>data.drivers.some((d:Driver)=>d.id===id)?id:data.drivers[0].id);}catch(e){setError(e instanceof Error?e.message:'Refresh unavailable.');}finally{setBusy(false);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(refresh,300000);return()=>clearInterval(timer);},[refresh]);
 const isConstructors=championship==='constructors';
 const competitors=isConstructors?season.constructors:season.drivers;
 const activeId=isConstructors?selectedConstructor:selected;
 const chooseEntrant=(id:string)=>{if(isConstructors)setSelectedConstructor(id);else setSelected(id);setHover(null);};
 const focus=competitors.find(d=>d.id===activeId)||competitors[0];
 const label=(d:Driver)=>isConstructors?d.name:short(d);
 const leader=competitors[0];
 const available=capacity(season.sessions,championship);
 const contenders=competitors.filter(d=>contenderStatus(season,d,championship)!=='Eliminated');
 const currentChampion=competitors.find(d=>competitors.filter(r=>r.id!==d.id).every(r=>isSafe(d,r,season.sessions,isConstructors?season.constructorCountbackAvailable:season.countbackAvailable,championship)));
 const prediction=useMemo(()=>isConstructors?projectConstructors(season,focus.id,mode,ownPair,rivalPair):project(season,focus.id,mode,own,rival),[season,focus.id,mode,own,rival,championship,ownPair,rivalPair]);
 const earliest=useMemo(()=>isConstructors?projectConstructors(season,focus.id,'earliest'):project(season,focus.id,'earliest'),[season,focus.id,championship]);
 const races=season.calendar.filter(r=>!r.completed);
 const rows=showAll?competitors:competitors.slice(0,8);
 const chart=[{name:'Now',type:'current',points:focus.points,ceiling:Math.max(...competitors.filter(d=>d.id!==focus.id).map(d=>d.points))+available,locked:prediction.already},...prediction.path];
 const minY=Math.floor(Math.min(...chart.flatMap(p=>[p.points,p.ceiling]))/25)*25-25;
 const maxY=Math.ceil(Math.max(...chart.flatMap(p=>[p.points,p.ceiling]))/25)*25+25;
 const x=(i:number)=>48+i*(632/Math.max(1,chart.length-1)),y=(v:number)=>195-(v-minY)/(maxY-minY)*163;
 const observed=hover===null?null:chart[hover];
 function setScenario(value:string){if(!['pressure','earliest','custom'].includes(value))throw new Error('Unknown scenario');setMode(value as Scenario);setHover(null);}
 useEffect(()=>{
   const registry=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;
   if(!registry?.registerTool)return;
   const controller=new AbortController();
   try{void Promise.resolve(registry.registerTool({name:'configure_championship_scenario',title:'Configure championship scenario',description:'Select a driver and scenario in the visible championship calculator.',inputSchema:{type:'object',properties:{driverId:{type:'string'},scenario:{type:'string',enum:['pressure','earliest','custom']},driverPosition:{type:'integer',minimum:1,maximum:11},rivalPosition:{type:'integer',minimum:1,maximum:11}},required:['driverId','scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{driverId:string;scenario:Scenario;driverPosition?:number;rivalPosition?:number})=>{
     const result=project(season,input.driverId,input.scenario,input.driverPosition??1,input.rivalPosition??2);
     setChampionship('drivers');setSelected(input.driverId);setMode(input.scenario);setOwn(input.driverPosition??1);setRival(input.rivalPosition??2);setHover(null);
     return {driver:season.drivers.find(d=>d.id===input.driverId)?.name,clinch:result.clinch,alreadyClinched:result.already};
   }},{signal:controller.signal})).catch(()=>{});}catch{ /* Browser support is optional. */ }
   try{void Promise.resolve(registry.registerTool({name:'configure_constructor_scenario',title:'Configure constructor championship scenario',description:'Select a constructor and two-car scenario in the visible championship calculator.',inputSchema:{type:'object',properties:{constructorId:{type:'string'},scenario:{type:'string',enum:['pressure','earliest','custom']},teamPositions:{type:'array',items:{type:'integer',minimum:1,maximum:11},minItems:2,maxItems:2},rivalPositions:{type:'array',items:{type:'integer',minimum:1,maximum:11},minItems:2,maxItems:2}},required:['constructorId','scenario'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{constructorId:string;scenario:Scenario;teamPositions?:number[];rivalPositions?:number[]})=>{
     const own=input.teamPositions??[1,2], rivals=input.rivalPositions??[3,4];
     const result=projectConstructors(season,input.constructorId,input.scenario,own,rivals);
     setChampionship('constructors');setSelectedConstructor(input.constructorId);setMode(input.scenario);setOwnPair(own);setRivalPair(rivals);setHover(null);
     return {constructor:season.constructors.find(c=>c.id===input.constructorId)?.name,clinch:result.clinch,alreadyClinched:result.already};
   }},{signal:controller.signal})).catch(()=>{});}catch{ /* Browser support is optional. */ }
   return()=>controller.abort();
 },[season]);
 return <>
  <header className="topbar"><div className="nav-wrap"><a className="brand" href="#"><span className="brand-icon"><Flag size={22} fill="currentColor"/></span><b>THE RUN-IN<span className="brand-dot">.</span></b><span className="brand-sub">FORMULA 1</span></a><nav aria-label="Page sections"><a href="#standings">Standings</a><a href="#calculator">Title calculator</a><a href="#calendar">Calendar</a><a href="#results">Season results</a></nav><span className="season-label">{season.year} SEASON <span>LOCAL</span></span></div></header>
  <main>
   <section className="intro"><div><div className="eyebrow"><span className="red-dash"/> {isConstructors?'THE CONSTRUCTORS’ CHAMPIONSHIP':'THE DRIVERS’ CHAMPIONSHIP'}</div><h1>Every point. <em>Every possibility.</em></h1><p>The standings, the races left, and the moment the title becomes inevitable.</p></div><div className="update"><span className={`status-dot ${verified&&season.source==='official'&&!error?'green':'amber'}`}/><span>{verified&&season.source==='official'&&!error?'Official F1 data':'Verified snapshot'}<small>Fetched {new Date(season.fetchedAt).toLocaleString('en-GB',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</small></span><button className="icon-button" onClick={refresh} disabled={busy} aria-label="Refresh official F1 data"><RefreshCw size={16} className={busy?'spinning':''}/></button></div></section>
   {(season.warning||error||!verified)&&<div className="data-note" role="status"><Info size={15}/>{error||season.warning||(busy?'Checking official F1 sources. The verified snapshot is shown while data loads.':'Verified snapshot shown until the official source is checked.')}</div>}
   <RadioGroup className="championship-switch" value={championship} onValueChange={v=>{setChampionship(v as Championship);setShowAll(false);setHover(null);}} aria-label="Championship mode"><label className={championship==='drivers'?'active':''}><RadioGroupItem value="drivers"/>Drivers</label><label className={championship==='constructors'?'active':''}><RadioGroupItem value="constructors"/>Constructors</label></RadioGroup>
   <section className="stats" aria-label="Championship overview"><div><span>CHAMPIONSHIP LEADER</span><strong>{label(leader)} <i style={{background:leader.color}}/></strong><small>{leader.points} points · {isConstructors?'Two-car total':leader.team}</small></div><div><span>LEAD OVER P2</span><strong>{leader.points-competitors[1].points}<small>PTS</small></strong><small>{label(competitors[1])} is closest</small></div><div><span>GRANDS PRIX REMAINING</span><strong>{races.length}<small>/{season.calendar.length}</small></strong><small>{season.sessions.filter(s=>s.type==='sprint').length} sprint{season.sessions.filter(s=>s.type==='sprint').length!==1?'s':''} still to race</small></div><div><span>POINTS STILL AVAILABLE</span><strong>{available}<small>PTS</small></strong><small>Maximum per {isConstructors?'constructor':'driver'}</small></div></section>
   <div className="workspace">
    <section id="standings" className="standings"><div className="section-heading"><div><span className="eyebrow">01 / THE GRID</span><h2>{isConstructors?'Constructor standings':'Driver standings'}</h2></div><span className="subtle-badge">{contenders.length} in contention</span></div>
      <div className="standing-legend"><span><i className="legend-line"/>Points scored</span><span><i className="legend-potential"/>Possible additional points</span></div>
      <Table className="standings-table"><TableHeader><TableRow><TableHead className="rank">POS</TableHead><TableHead>{isConstructors?'CONSTRUCTOR':'DRIVER'}</TableHead><TableHead className="bar-heading">CHAMPIONSHIP POINTS</TableHead><TableHead className="numeric">PTS</TableHead><TableHead className="numeric">GAP</TableHead></TableRow></TableHeader><TableBody>{rows.map(d=>{const eliminated=contenderStatus(season,d,championship)==='Eliminated';return <TableRow key={d.id} className={`${activeId===d.id?'selected-row':''} ${eliminated?'eliminated-row':''}`}><TableCell className="rank">{String(d.position).padStart(2,'0')}</TableCell><TableCell className="driver-cell"><button onClick={()=>{chooseEntrant(d.id);}} aria-label={`Calculate title scenarios for ${d.name}`} aria-pressed={activeId===d.id}><span className="team-line" style={{background:d.color}}/><OfficialImage src={isConstructors?d.teamLogoUrl:d.portraitUrl} label={`${d.name} ${isConstructors?'logo':'portrait'}`} fallback={d.code} className={isConstructors?'constructor-logo':'driver-portrait'} color={d.color}/><span className="driver-name"><b>{d.name}</b><small>{!isConstructors&&<OfficialImage src={d.teamLogoUrl} label={`${d.team} logo`} fallback={d.team.slice(0,1)} className="team-logo" color={d.color}/>} {isConstructors?`${d.finishes[0]} GP wins · 2 cars`:d.team}{eliminated?' · Eliminated':''}</small></span>{activeId===d.id&&<ChevronRight size={15}/>}</button></TableCell><TableCell className="bar-cell"><div className="points-track" aria-label={`${d.points} points, maximum final total ${d.points+available}`}><div style={{width:`${d.points/(leader.points+available)*100}%`,background:d.color}}/><span className="potential" style={{width:`${available/(leader.points+available)*100}%`}}/></div></TableCell><TableCell className="numeric score">{d.points}</TableCell><TableCell className="numeric gap">{d.position===1?'—':`−${leader.points-d.points}`}</TableCell></TableRow>})}</TableBody></Table>
      <button className="expand-button" onClick={()=>setShowAll(!showAll)}>{showAll?'Show top 8':`Show all ${competitors.length} ${isConstructors?'constructors':'drivers'}`} <ChevronRight size={14} className={showAll?'rotate-up':''}/></button>
      <div className="standings-note"><Info size={15}/><p>{currentChampion?`${currentChampion.name} has mathematically secured the title.`:'The title is still open.'} A {isConstructors?'constructor':'driver'} is eliminated when even their maximum remaining score cannot win the championship.</p></div>
    </section>
    <section id="calculator" className="calculator"><div className="section-heading"><div><span className="eyebrow">02 / THE BREAK-EVEN</span><h2>When can they clinch it?</h2></div><Trophy size={20}/></div>
      <label className="field-label" htmlFor="driver-select">{isConstructors?'CHOOSE A CONSTRUCTOR':'CHOOSE A DRIVER'}</label><Select value={focus.id} onValueChange={chooseEntrant}><SelectTrigger id="driver-select" className="driver-select"><SelectValue/></SelectTrigger><SelectContent>{competitors.map(d=><SelectItem key={d.id} value={d.id}>{d.name} · {d.points} pts</SelectItem>)}</SelectContent></Select>
      <label className="field-label scenario-label">ASSUME FOR EACH REMAINING SESSION</label><RadioGroup value={mode} onValueChange={setScenario} className="scenario-options" aria-label="Championship scenario"><label className={mode==='pressure'?'scenario active':'scenario'}><RadioGroupItem value="pressure"/><span><b>Keep the pressure on</b><small>{isConstructors?'Team finishes P1/P2; rivals bounded by P3/P4':'Driver wins; every rival is bounded by P2'}</small></span></label><label className={mode==='earliest'?'scenario active':'scenario'}><RadioGroupItem value="earliest"/><span><b>Earliest possible</b><small>{isConstructors?'Team finishes P1/P2; all rivals score zero':'Driver wins; all rivals score zero'}</small></span></label><label className={mode==='custom'?'scenario active':'scenario'}><RadioGroupItem value="custom"/><span><b>Set your own scenario</b><small>{isConstructors?'Choose finishes for both cars and rival cars':'Choose the driver’s finish and rival ceiling'}</small></span></label></RadioGroup>
      {mode==='custom'&&isConstructors&&<div className="custom-controls constructor-controls">{[0,1,2,3].map(i=>{const positions=[...ownPair,...rivalPair];const p=positions[i];return <div key={i}><label className="field-label" htmlFor={`constructor-car-${i}`}>{i<2?`TEAM CAR ${i+1}`:`RIVAL CAR ${i-1}`}</label><Select value={String(p)} onValueChange={v=>{const setter=i<2?setOwnPair:setRivalPair;setter(old=>old.map((value,index)=>index===i%2?Number(v):value));}}><SelectTrigger id={`constructor-car-${i}`}><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:11},(_,j)=>j+1).filter(value=>value===11||value===p||!positions.includes(value)).map(value=><SelectItem key={value} value={String(value)}>{positionLabel(value)}</SelectItem>)}</SelectContent></Select></div>;})}</div>}
      {mode==='custom'&&!isConstructors&&<div className="custom-controls"><div><label className="field-label" htmlFor="own-pos">DRIVER FINISH</label><Select value={String(own)} onValueChange={v=>{const p=Number(v);setOwn(p);if(p===rival&&p<=10)setRival(p===1?2:1);}}><SelectTrigger id="own-pos"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:11},(_,i)=>i+1).map(p=><SelectItem key={p} value={String(p)}>{positionLabel(p)}</SelectItem>)}</SelectContent></Select></div><div><label className="field-label" htmlFor="rival-pos">RIVALS’ BEST FINISH</label><Select value={String(rival)} onValueChange={v=>setRival(Number(v))}><SelectTrigger id="rival-pos"><SelectValue/></SelectTrigger><SelectContent>{Array.from({length:11},(_,i)=>i+1).filter(p=>p!==own||p===11).map(p=><SelectItem key={p} value={String(p)}>{positionLabel(p)}</SelectItem>)}</SelectContent></Select></div></div>}
      <div className="selected-driver"><OfficialImage src={isConstructors?focus.teamLogoUrl:focus.portraitUrl} label={`${focus.name} ${isConstructors?'logo':'portrait'}`} fallback={focus.code} className={isConstructors?'constructor-logo':'driver-portrait'} color={focus.color}/><div><b>{focus.name}</b><span>{!isConstructors&&<OfficialImage src={focus.teamLogoUrl} label={`${focus.team} logo`} fallback={focus.team.slice(0,1)} className="team-logo" color={focus.color}/>} {isConstructors?`${focus.finishes[0]} Grand Prix wins · 2 cars`:focus.team}<i style={{background:focus.color}}/></span></div></div>
      <div className={`result-card ${prediction.clinch?'can-clinch':'cannot-clinch'}`} aria-live="polite"><div className="result-top"><span>{prediction.already?'TITLE SECURED':prediction.clinch?'PROJECTED CLINCH':'NO CLINCH IN THIS SCENARIO'}</span>{prediction.clinch?<Trophy size={18}/>:<Flag size={18}/>}</div><h3>{prediction.clinch?.name||'Still a fight to the finish.'}{prediction.clinch&&prediction.clinch.type!=='current'&&<ArrowUpRight size={27}/>}</h3><div className="result-date">{prediction.clinch?.type==='current'?'Uncatchable on the current standings':prediction.clinch?`${date(prediction.clinch.start)} · ${prediction.clinch.type==='sprint'?'Sprint':'Grand Prix'} · Round ${prediction.clinch.round}`:`${label(focus)} cannot guarantee the title under these results.`}</div>{prediction.clinch&&prediction.clinch.type!=='current'&&<div className="result-metrics"><div><span>{focus.code} PROJECTED</span><b>{prediction.path[prediction.clinch.index].points}<small> pts</small></b></div><div><span>RIVAL FINAL CEILING</span><b>{prediction.path[prediction.clinch.index].ceiling}<small> pts</small></b></div></div>}</div>
      <p className="calculator-footnote">{mode==='earliest'?'This is the earliest mathematical opportunity, assuming every rival scores zero. It is not a prediction.':'Each rival is evaluated separately at the chosen ceiling. Actual rivals cannot share the same positions, so this gives a conservative guarantee.'} {earliest.clinch&&!prediction.already&&mode!=='earliest'&&<>Earliest mathematical opportunity: <b>{earliest.clinch.name}</b>.</>}</p>
    </section>
   </div>
   <section className="projection"><div className="section-heading"><div><span className="eyebrow">03 / THE CROSSOVER</span><h2>The path to an uncatchable lead</h2></div><div className="chart-legend"><span><i className="legend-line red"/>{focus.code} projected points</span><span><i className="legend-dashed"/>Highest rival’s final ceiling</span></div></div><p className="chart-description">The title is secured once the {isConstructors?'constructor’s':'driver’s'} points beat every rival’s maximum final total—or win the countback on a tie.</p><div className="chart-wrap"><svg viewBox="0 0 720 240" role="img" aria-label={`Projected points for ${focus.name} compared with the largest rival championship ceiling`}>
     {Array.from({length:5},(_,i)=>minY+(maxY-minY)*i/4).map(v=><g key={v}><line x1="48" y1={y(v)} x2="680" y2={y(v)} stroke="#e8e6e2"/><text x="34" y={y(v)+4} textAnchor="end" className="chart-tick">{Math.round(v)}</text></g>)}
     {prediction.clinch&&prediction.clinch.type!=='current'&&<rect x={x(prediction.clinch.index+1)} y="18" width={Math.max(2,680-x(prediction.clinch.index+1))} height="180" fill="#eef4eb"/>}
     <polyline points={chart.map((p,i)=>`${x(i)},${y(p.ceiling)}`).join(' ')} fill="none" stroke="#898a8c" strokeWidth="2" strokeDasharray="5 5"/><polyline points={chart.map((p,i)=>`${x(i)},${y(p.points)}`).join(' ')} fill="none" stroke="#ed3b2b" strokeWidth="3"/>
     {chart.map((p,i)=><g key={i} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)}><circle cx={x(i)} cy={y(p.points)} r="4" fill="#ed3b2b"/><text x={x(i)} y="222" textAnchor="middle" className="chart-tick">{i===0?'Now':season.sessions[i-1].name==='Singapore'?(p.type==='sprint'?'SGP S':'SGP GP'):season.sessions[i-1].name==='United States'?'USA':season.sessions[i-1].name==='Abu Dhabi'?'ABU':season.sessions[i-1].name.slice(0,3).toUpperCase()}</text><rect x={x(i)-16} y="12" width="32" height="214" fill="transparent"/></g>)}
   </svg></div><div className="chart-readout" aria-live="polite">{observed?<><b>{observed.name}{observed.type==='sprint'?' sprint':''}</b><span>{focus.code}: {observed.points} pts</span><span>Rival ceiling: {observed.ceiling} pts</span>{observed.locked&&<span className="clinch-tag"><Check size={12}/> Title secured</span>}</>:<><span className="chart-help">Hover over a round to compare the totals.</span><span>Projected results · {mode==='earliest'?'earliest possible':mode==='pressure'?(isConstructors?'P1/P2 vs P3/P4':'wins vs P2'):isConstructors?`${ownPair.map(positionLabel).join('/')} vs ${rivalPair.map(positionLabel).join('/')}`:`${positionLabel(own)} vs ${positionLabel(rival)}`}</span></>}</div>
     <details className="projection-details"><summary>View the calculation by session</summary><Table><TableHeader><TableRow><TableHead>SESSION</TableHead><TableHead className="numeric">{focus.code} POINTS</TableHead><TableHead className="numeric">RIVAL CEILING</TableHead><TableHead className="numeric">STATUS</TableHead></TableRow></TableHeader><TableBody>{prediction.path.map((p:typeof prediction.path[number])=><TableRow key={p.start+p.type}><TableCell>{p.name} {p.type==='sprint'?'Sprint':'GP'}</TableCell><TableCell className="numeric">{p.points}</TableCell><TableCell className="numeric">{p.ceiling}</TableCell><TableCell className="numeric">{p.locked?'Secured':p.margin===0?'Countback / tie':'Open'}</TableCell></TableRow>)}</TableBody></Table></details>
   </section>
   <section id="calendar" className="calendar"><div className="section-heading"><div><span className="eyebrow">04 / THE FINAL STRETCH</span><h2>{races.length?'The races still to come':'The season is complete'}</h2></div><a className="source-link" href={season.sources.calendar} target="_blank" rel="noreferrer">Official calendar <ArrowUpRight size={14}/></a></div><div className="race-grid">{races.map((r,i)=>{const max=capacity(season.sessions.filter(s=>s.slug===r.slug),championship);const clinch=prediction.clinch&&prediction.clinch.type!=='current'&&prediction.clinch.slug===r.slug;return <a href={r.url} target="_blank" rel="noreferrer" className={`race-card ${clinch?'clinch-race':''}`} key={r.slug}><div className="race-top"><span>R{String(r.round).padStart(2,'0')}</span>{i===0?<span className="next-label">UP NEXT</span>:<ArrowUpRight size={14}/>}</div><div className="race-date">{date(r.date)}</div><h3>{r.name}</h3><CircuitImage src={r.circuitImageUrl} name={r.name}/><div className="race-bottom"><span>{r.sprint?<><Zap size={12}/> Sprint weekend</>:'Grand Prix'}</span><b>{max} PTS</b></div>{clinch&&<div className="race-clinch"><Trophy size={12}/> Projected clinch</div>}</a>})}</div><p className="calendar-note">Race dates are shown in your local timezone ({Intl.DateTimeFormat().resolvedOptions().timeZone}). Sprint points are included in the weekend total.</p></section>
   <SeasonResults season={season} championship={championship}/>
   <section className="method"><div className="method-title"><Info size={18}/><h3>The math behind the moment</h3></div><div className="method-grid"><p><b>{isConstructors?'43 for a GP one-two. 15 for a sprint one-two.':'25 for a win. 8 for a sprint.'}</b> Standard Grand Prix points: 25, 18, 15, 12, 10, 8, 6, 4, 2, 1. Sprint points: 8 through 1. No fastest-lap bonus. {isConstructors&&'Constructor points combine both cars.'}</p><p><b>A lead nobody can close.</b> After each session, we add all remaining available points to every rival’s projected total. The chosen {isConstructors?'constructor':'driver'} must beat them all.</p><p><b>Ties need a countback.</b> Equal points use Grand Prix wins, then seconds, thirds, and so on. {(isConstructors?season.constructorCountbackAvailable:season.countbackAvailable)?(isConstructors?'Both cars’ GP finishes are counted; sprint finishes are excluded.':'Completed race results are included.'):'Countback data is unavailable, so ties stay open.'} Unresolved countbacks stay open.</p></div><div className="assumptions"><span>Assumptions</span> Full points in future sessions; the published calendar stays unchanged; no later penalties. Completed sprints are removed only when the source marks them complete.</div></section>
   <footer><span className="footer-brand"><Flag size={15}/> THE RUN-IN<span className="brand-dot">.</span></span><span>Independent local tool. Not affiliated with Formula 1.</span><div><a href={isConstructors?season.sources.constructors:season.sources.standings} target="_blank" rel="noreferrer">{isConstructors?'F1 constructors':'F1 standings'} <ArrowUpRight size={12}/></a><a href={season.sources.rules} target="_blank" rel="noreferrer">FIA rules <ArrowUpRight size={12}/></a></div></footer>
  </main>
 </>;
}
